server:
  port: 8762
spring:
  application:
    name: proxy
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/


jwt.secret:
  SuperSecret

login.service.name:
  login-service

